spring.application.name=academy

spring.datasource.url=jdbc:mysql://localhost:3306
spring.datasource.username=root
spring.datasource.password=Afterthefall17!

spring.main.allow-bean-definition-overriding=true


