spring.application.name=academy
spring.datasource.url=jdbc:mysql://localhost:3306/academy_db
spring.datasource.username=academy
spring.datasource.password=@@vlc2clv@@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
